from flask import Flask, render_template, request, send_file
import csv
import os
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

app = Flask(__name__)

# Load data from CSV
def load_person_by_name(search_name):
    if os.path.exists('dataset.csv'):
        with open('dataset.csv', 'r', encoding='utf-8') as file:
            reader = csv.DictReader(file)
            for row in reader:
                if row['name'].strip().lower() == search_name.strip().lower():
                    return row
    return None


@app.route('/')
def home():
    return render_template('index.html')


@app.route('/result', methods=['GET', 'POST'])
def result():
    person = None
    search_name = ""

    if request.method == 'POST':
        search_name = request.form.get('suspect_name', '').strip()
        person = load_person_by_name(search_name)

    return render_template('result.html', person=person, search_name=search_name)


@app.route('/download_report/<name>')
def download_report(name):
    person = load_person_by_name(name)

    if not person:
        return "No record found!"

    # Create reports folder if not exists
    os.makedirs('reports', exist_ok=True)

    pdf_filename = f"{person['case_id']}_report.pdf"
    pdf_path = os.path.join('reports', pdf_filename)

    # Create PDF
    c = canvas.Canvas(pdf_path, pagesize=letter)
    width, height = letter

    y = height - 50

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, "Social Media Evidence Report")
    y -= 30

    c.setFont("Helvetica", 11)

    lines = [
        f"Case ID: {person['case_id']}",
        f"Officer Name: {person['officer_name']}",
        f"Suspect Name: {person['name']}",
        f"Platform: {person['platform']}",
        f"Profile URL: {person['profile_url']}",
        f"Username / ID: {person['social_id']}",
        "",
        "Auto Person Information",
        f"Detected Name: {person['detected_name']}",
        f"Contact: {person['contact']}",
        f"Followers / Friends: {person['followers']}",
        f"Following: {person['following']}",
        f"Bio: {person['bio']}",
        "",
        "Risk Analysis",
        f"Risk Level: {person['risk_level']}",
        f"Suspicious History: {person['suspicious_history']}",
        f"Keywords Found: {person['keywords']}",
        "",
        "Evidence Screenshots",
        f"1. {person['screenshot1']}",
        f"2. {person['screenshot2']}",
        f"3. {person['screenshot3']}",
        "",
        "Generated by Social Media Investigation Tool"
    ]

    for line in lines:
        c.drawString(50, y, line)
        y -= 18

        if y < 50:
            c.showPage()
            c.setFont("Helvetica", 11)
            y = height - 50

    c.save()

    return send_file(pdf_path, as_attachment=True)


if __name__ == '__main__':
    app.run(debug=True)